# POST http://localhost:3000/api/auth/register http/1.1
# Content-Type: application/json

# {
#   "email":"fnsws",
#   "password":"jfodwjfow",
#   "uuid":1,
#   "inputCode":1
# }


# POST http://localhost:3000/api/auth/login http/1.1
# Content-Type: application/json

# {
#   "email":"fnws",
#   "password":"jfodwjfow"
# }

# GET http://localhost:3000/api/auth/captcha http/1.1
# Content-Type: application/json